version: '3.7'

services:
  web:
    build: ./application
    command: flask run -h 0.0.0.0
    volumes:
      - ./application/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev