version: '3.7'

services:
  web:
    build: ./application
    container_name: flask-api
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres -d postgres"
      interval: 30s
      timeout: 10s
      retries: 5
    env_file:
      - ./.env.db

volumes:
  postgres_data:
