version: '3.7'

services:
  web:
    build: ./application
    container_name: flask-api
    command: flask run -h 0.0.0.0
    volumes:
      - ./application/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    environment:
      DB_URI: postgresql://test_user:qwer1234@db:5432/api_db
    networks:
      - ryllari_net
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api_db
    networks:
      - ryllari_net

volumes:
  postgres_data:

networks:
  ryllari_net:
