"""empty message

Revision ID: cb523eb05c70
Revises: 
Create Date: 2020-08-21 21:47:43.927558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb523eb05c70'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('did_number',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=17), nullable=True),
    sa.Column('monthyPrice', sa.Numeric(precision=8, scale=2, decimal_return_scale=2), nullable=True),
    sa.Column('setupPrice', sa.Numeric(precision=8, scale=2, decimal_return_scale=2), nullable=True),
    sa.Column('currency', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('did_number')
    # ### end Alembic commands ###
