"""empty message

Revision ID: 91879b3d3703
Revises: cb523eb05c70
Create Date: 2020-08-23 19:58:03.420084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91879b3d3703'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('did_number',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=17), nullable=True),
    sa.Column('monthyPrice', sa.Numeric(precision=8, scale=2, decimal_return_scale=2), nullable=True),
    sa.Column('setupPrice', sa.Numeric(precision=8, scale=2, decimal_return_scale=2), nullable=True),
    sa.Column('currency', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('did_number')
    # ### end Alembic commands ###
